- name: Joe's awesome test playbook
  hosts: localhost
  connection: local
  tasks:
    - name: Clone repo, update file, delete repo
      block:
 
        - name: debug key
          debug:
            var: secret_key

        - name: pull down the repo
          git:
            repo: git@github.com:joej164/awx_test.git
            dest: awx_test
            key_file: "{{ secret_key }}"
        
        - name: make output dictionary
          set_fact:
            template_vars: "{{ template_vars|default([]) | combine({item.key: item.value}) }}"
          with_dict: "{{ hostvars['localhost'] }}"
          when: "'joe' in item.key"
        
        - name: fill out a template
          template:
            src: test_template.j2
            dest: awx_test/output/test_out.txt

        - name: add the file
          shell: "{{ item }}"
          args:
            chdir: awx_test
          with_items:
            - "git add output/test_out.txt"
            - "git commit -m 'adding test file'"
            - "git config core.sshCommand 'ssh -i {{ secret_key }} -F /dev/null'"
            - "git push origin master"

      always:
        - name: delete git repo
          file:
            state: absent
            path: awx_test/
