- name: Joe's awesome test playbook
  hosts: localhost
  connection: local
  tasks:
    - name: get the local directory
      shell: ls -al
      register: out
    - name: print out the variables
      debug:
        var: out
    - name: output more data
      debug:
        var: "{{ item }}"
      with_items:
       - joe_color
       - joe_name
       - joe_quest
      when: joe_color is defined

    - name: fill out a template
      template:
        src: test_template.j2
        dest: test_out.txt

    - name: get the local directory
      shell: ls -al
      register: out
    - name: print out the variables
      debug:
        var: out

