- name: Joe's awesome test playbook
  hosts: localhost
  connection: local
  tasks:
    - name: get the local directory
      shell: ls -al
      register: out
    - name: print out the variables
      debug:
        var: out
    - name: output more data
      debug:
        var: "{{ item }}"
      with_items:
       - joe_color
       - joe_name
       - joe_quest
      when: joe_color is defined
    
    - name: pull down the repo
      git:
        repo: git@github.com:joej164/awx_test.git
        dest: awx_test

    - name: fill out a template
      template:
        src: test_template.j2
        dest: awx_test/output/test_out.txt

    - name:
      assert: 
        that: False

    - name: add the file
      shell: "{{ item }}"
      args:
        chdir: awx_test
      with_items:
        - "git add test_out.txt"
        - "git commit -m 'adding test file'"
        - "git push origin master"

