- name: Joe's test playbook
  hosts: all
  tasks:
    - name: run a command
      shell: ip address
      register: out

    - name: output data
      debug:
        var: 
          - out.stdout
          - joe_color
          - joe_name
          - joe_quest
