- name: Joe's test playbook
  hosts: all
  tasks:
    - name: run a command
      shell: ip address
      register: out

    - name: output data
      debug:
        var: 
          - out.stdout
          - joe_color
          - joe_name
          - joe_quest
    
    - name: output more data
      debug:
        var: "{{ item }}"
      with_items:
       - out.stdout
       - joe_color
       - joe_name
       - joe_quest

