- name: Joe's awesome test playbook
  hosts: localhost
  connection: local
  tasks:
    - name: output data
      debug:
        var: 
          out
     
    - name: output more data
      debug:
        var: "{{ item }}"
      with_items:
       - joe_color
       - joe_name
       - joe_quest
      when: joe_color is defined

    - name: local os
      shell: ls -al
      register: ls_out

    - name: output results
      debug:
        var: ls_out

